backend:
  name: git-gateway
  branch: master

  media_folder: "static/images"
  public_folder: "images"

  collections:
    - name: "isgs"
      label: "Blogeintrag"
      folder: "content/post"
      create: true
      slug: "{{year}}--{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Datum", name: "date", widget: "datetime"}
        - {label: "Tags", name: "tags", widget: "string"}
        - {label: "Kategorie", name: "categories", widget: "string", default:"Gravelserie"}
        - {label: 'Text hier eingeben', name: 'body', widget: 'markdown' }
    